# ========================================
# Site Configuration
# ========================================

title: Zachary L. Skidmore
#email:
description: >
  Bioinformatics, data science, and reflections at the intersection of technology and meaning.
baseurl: ""          # Leave empty unless deploying under a subpath (e.g. /blog)
url: "https://zlskidmore.github.io"  # Change to your site's canonical URL

# Social / SEO
github_username: zlskidmore

social:
  name: Zachary L. Skidmore
  links:
    - https://github.com/zlskidmore
    - https://bsky.app/profile/zlskidmore.bsky.social

# ========================================
#  Build Settings
# ========================================

theme: minima        # Can be overridden if you're using custom layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: assets/css
  style: compressed

# Optional: Clean URLs (no .html)
permalink: /:categories/:title/

# ========================================
# Collections & Defaults
# ========================================

collections:
  posts:
    output: true
    permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Zach Skidmore"
      comments: false

# ========================================
# Exclusions
# ========================================

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md

